language: ruby

services:
  - docker

before_install:
  - docker build -t xiaodi93/dcnmp-php73:latest --build-arg PHP_VERSION=7.3 PHP_SWOOLE=4.4.7 PHP_REDIS=4.2.0 PHP_MEMCACHED=3.1.3 PHP_PDO_SQLSRV=5.6.1 .
  - docker build -t xiaodi93/dcnmp-php73:debug --build-arg PHP_VERSION=7.3 PHP_SWOOLE=4.4.7 PHP_REDIS=4.2.0 PHP_MEMCACHED=3.1.3 PHP_PDO_SQLSRV=5.6.1 PHP_XDEBUG=2.6.1 .
  - docker build -t xiaodi93/dcnmp-php72:latest --build-arg PHP_VERSION=7.2 PHP_SWOOLE=4.4.7 PHP_REDIS=4.2.0 PHP_MEMCACHED=3.1.3 PHP_PDO_SQLSRV=5.6.1 .
  - docker build -t xiaodi93/dcnmp-php72:debug --build-arg PHP_VERSION=7.2 PHP_SWOOLE=4.4.7 PHP_REDIS=4.2.0 PHP_MEMCACHED=3.1.3 PHP_PDO_SQLSRV=5.6.1 PHP_XDEBUG=2.6.1 .
  - docker build -t xiaodi93/dcnmp-php71:latest --build-arg PHP_VERSION=7.1 PHP_SWOOLE=4.4.7 PHP_REDIS=4.2.0 PHP_MEMCACHED=3.1.3 PHP_PDO_SQLSRV=5.6.1 .
  - docker build -t xiaodi93/dcnmp-php71:debug --build-arg PHP_VERSION=7.1 PHP_SWOOLE=4.4.7 PHP_REDIS=4.2.0 PHP_MEMCACHED=3.1.3 PHP_PDO_SQLSRV=5.6.1 PHP_XDEBUG=2.6.1 .
  
script:
  - docker images
  
after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xiaodi93/dcnmp-php73
  - docker push xiaodi93/dcnmp-php72
  - docker push xiaodi93/dcnmp-php71
